name: EvasionPathsEnv
channels:
  - conda-forge
  - defaults
dependencies:
# Interpreter
  - python >=3.10
  - setuptools
  - pytest
# Core
  - gudhi >=3.6
  - networkx
  - numpy
  - scipy
  - pandas
  - treelib
# Apps
  - joblib
  - ffmpeg
  - matplotlib
