name: EvasionPaths-env
channels:
  - conda-forge
dependencies:
  - ffmpeg
  - gudhi=3.0.0
  - matplotlib
  - networkx
  - numpy
  - numpy-base
  - python=3.6.9
  - scipy
  - setuptools
  - joblib
  - treelib

