name: WeightedEvasionPaths-env
channels:
  - conda-forge
dependencies:
  - ffmpeg
  - matplotlib
  - networkx
  - numpy
  - numpy-base
  - python=3.6.9
  - scipy
  - setuptools
  - joblib
  - pybind11

